# Generated by Django 5.0 on 2024-01-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="label",
            field=models.CharField(default="ASD", max_length=255),
            preserve_default=False,
        ),
    ]
