# Generated by Django 5.0.1 on 2024-01-09 00:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0002_stockitem_label"),
    ]

    operations = [
        migrations.RenameField(
            model_name="import",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="import",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="importitem",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="importitem",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="stockitem",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="stockitem",
            old_name="updated",
            new_name="updated_at",
        ),
    ]
