# Generated by Django 5.0.1 on 2024-02-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0002_alter_import_description_alter_import_title_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="import",
            options={"verbose_name": "Увоз", "verbose_name_plural": "Увози"},
        ),
        migrations.AlterModelOptions(
            name="stockitem",
            options={"verbose_name": "Предмет", "verbose_name_plural": "Предмети"},
        ),
        migrations.RemoveField(
            model_name="importitem",
            name="price",
        ),
        migrations.AddField(
            model_name="importitem",
            name="price_no_vat",
            field=models.PositiveIntegerField(default=0, verbose_name="Цена без ДДВ"),
        ),
        migrations.AddField(
            model_name="importitem",
            name="price_vat",
            field=models.PositiveIntegerField(default=0, verbose_name="Цена со ДДВ"),
        ),
        migrations.AlterField(
            model_name="importitem",
            name="quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="Количина"),
        ),
    ]
