# Generated by Django 5.0.1 on 2024-02-27 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0003_alter_import_options_alter_stockitem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="importitem",
            options={
                "verbose_name": "Увозен Продукт",
                "verbose_name_plural": "Увозени Продукти",
            },
        ),
        migrations.AlterModelOptions(
            name="stockitem",
            options={
                "verbose_name": "Магацински Продукт",
                "verbose_name_plural": "Магацински Продукт",
            },
        ),
    ]
