# Generated by Django 5.0.1 on 2024-03-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0005_importitem_price_vat_and_customs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockitem",
            name="sku",
            field=models.CharField(
                db_index=True, max_length=255, unique=True, verbose_name="SKU"
            ),
        ),
    ]
