# Generated by Django 5.0.1 on 2024-03-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0006_alter_stockitem_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="reserved_stock",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Резервирана залиха"
            ),
        ),
    ]
