# Generated by Django 5.0.1 on 2024-03-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0007_stockitem_reserved_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockitem",
            name="reserved_stock",
        ),
        migrations.AddField(
            model_name="importitem",
            name="reserved_stock",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Резервирана залиха"
            ),
        ),
    ]
