# Generated by Django 5.0.1 on 2024-03-17 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0009_orderitem_stock_item"),
        ("stock", "0008_remove_stockitem_reserved_stock_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservedStockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Количина"),
                ),
                (
                    "import_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stock.importitem",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cart.orderitem"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
