# Generated by Django 5.0.1 on 2024-03-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0010_alter_importitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservedstockitem",
            name="initial_quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Почетна количина"
            ),
        ),
        migrations.AddField(
            model_name="reservedstockitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RESERVED", "Reserved"),
                    ("DEPLETED", "Depleted"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
