# Generated by Django 5.0.1 on 2024-03-17 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0011_reservedstockitem_initial_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservedstockitem",
            name="import_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="stock.importitem",
            ),
        ),
    ]
