# Generated by Django 5.0.1 on 2024-03-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0012_alter_reservedstockitem_import_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="importitem",
            name="initial_quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Увезена количина"
            ),
        ),
        migrations.AlterField(
            model_name="importitem",
            name="quantity",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Моментална залиха"
            ),
        ),
        migrations.AlterField(
            model_name="reservedstockitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ARCHIVED", "Archived"),
                    ("DEPLETED", "Depleted"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
