# Generated by Django 5.0.1 on 2024-03-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0013_importitem_initial_quantity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockitem",
            options={
                "verbose_name": "Stock Item",
                "verbose_name_plural": "Stock Items",
            },
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="stock",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Вистинска залиха, без резервирана"
            ),
        ),
    ]
