# Generated by Django 5.0.1 on 2024-05-06 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0030_remove_orderitem_reserved_stock_items"),
        ("stock", "0014_alter_stockitem_options_alter_stockitem_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservedstockitem",
            name="order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cart.orderitem",
                verbose_name="reserved_stock_items",
            ),
        ),
    ]
