# Generated by Django 5.0.1 on 2024-05-06 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0030_remove_orderitem_reserved_stock_items"),
        ("stock", "0015_alter_reservedstockitem_order_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservedstockitem",
            name="order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reserved_stock_items",
                to="cart.orderitem",
            ),
        ),
    ]
