# Generated by Django 5.0.1 on 2024-05-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0017_importitem_ad_spend_alter_importitem_parentimport_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importitem",
            name="ad_spend",
        ),
        migrations.AddField(
            model_name="import",
            name="ad_spend",
            field=models.IntegerField(default=0, verbose_name="Ad Spend"),
        ),
    ]
