# Generated by Django 5.0.1 on 2024-05-17 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("shop", "0046_alter_shopclient_options_shopclient_display_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("campaign_id", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Summary",
                "verbose_name_plural": "Campaign Summaries",
            },
        ),
        migrations.CreateModel(
            name="CampaignEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity_ordered",
                    models.PositiveIntegerField(
                        verbose_name="Quantity of OrderItems Ordered"
                    ),
                ),
                (
                    "total_sales_price",
                    models.PositiveIntegerField(
                        verbose_name="Total Sale Price of all OrderItems"
                    ),
                ),
                (
                    "total_cost_price",
                    models.PositiveIntegerField(
                        verbose_name="Total Cost Price of all OrderItems"
                    ),
                ),
                (
                    "total_profit",
                    models.PositiveIntegerField(
                        verbose_name="Total Profit of all OrderItems"
                    ),
                ),
                (
                    "total_neto",
                    models.PositiveIntegerField(
                        verbose_name="Total Neto of all OrderItems"
                    ),
                ),
                (
                    "advertisement_cost",
                    models.PositiveIntegerField(
                        verbose_name="Total Advertisement Cost"
                    ),
                ),
                (
                    "product_sale_price",
                    models.PositiveIntegerField(verbose_name="Product Sale Price"),
                ),
                (
                    "product_cost_price",
                    models.PositiveIntegerField(verbose_name="Product Cost Price"),
                ),
                (
                    "product_profit",
                    models.PositiveIntegerField(verbose_name="Product Profit"),
                ),
                (
                    "product_neto",
                    models.PositiveIntegerField(verbose_name="Product Neto"),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.campaignsummary",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
