# Generated by Django 5.0.1 on 2024-05-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0003_campaignsummary_campaign_id_campaignsummary_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaignentry",
            old_name="campaign",
            new_name="parent",
        ),
        migrations.RemoveField(
            model_name="campaignentry",
            name="product_neto",
        ),
        migrations.RemoveField(
            model_name="campaignentry",
            name="total_neto",
        ),
        migrations.AddField(
            model_name="campaignentry",
            name="import_item_data",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaignentry",
            name="product_stock_left",
            field=models.IntegerField(
                default=0, verbose_name="Product Stock Left After Campaign"
            ),
        ),
        migrations.AlterField(
            model_name="campaignentry",
            name="advertisement_cost",
            field=models.IntegerField(
                default=0, verbose_name="Total Advertisement Cost"
            ),
        ),
        migrations.AlterField(
            model_name="campaignentry",
            name="product_cost_price",
            field=models.IntegerField(default=0, verbose_name="Product Cost Price"),
        ),
        migrations.AlterField(
            model_name="campaignentry",
            name="product_profit",
            field=models.IntegerField(default=0, verbose_name="Product Profit"),
        ),
        migrations.AlterField(
            model_name="campaignentry",
            name="product_sale_price",
            field=models.IntegerField(default=0, verbose_name="Product Sale Price"),
        ),
        migrations.AlterField(
            model_name="campaignentry",
            name="quantity_ordered",
            field=models.IntegerField(
                default=0, verbose_name="Quantity of OrderItems Ordered"
            ),
        ),
        migrations.AlterField(
            model_name="campaignentry",
            name="total_cost_price",
            field=models.IntegerField(
                default=0, verbose_name="Total Cost Price of all OrderItems"
            ),
        ),
        migrations.AlterField(
            model_name="campaignentry",
            name="total_profit",
            field=models.IntegerField(
                default=0, verbose_name="Total Profit of all OrderItems"
            ),
        ),
        migrations.AlterField(
            model_name="campaignentry",
            name="total_sales_price",
            field=models.IntegerField(
                default=0, verbose_name="Total Sale Price of all OrderItems"
            ),
        ),
    ]
