# Generated by Django 5.0.1 on 2024-05-18 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0004_rename_campaign_campaignentry_parent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaignentry",
            name="product_profit",
        ),
        migrations.RemoveField(
            model_name="campaignentry",
            name="total_profit",
        ),
        migrations.AlterField(
            model_name="campaignentry",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="analytics.campaignsummary",
            ),
        ),
    ]
