# Generated by Django 5.0.1 on 2024-05-21 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0005_remove_campaignentry_product_profit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignentry",
            name="for_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 5, 21, 3, 46, 50, 76442, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date for which the data is valid",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="campaignentry",
            name="advertisement_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Total Advertisement Cost",
            ),
        ),
    ]
