# Generated by Django 5.0.1 on 2024-05-21 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0008_remove_campaignentry_for_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignentry",
            name="for_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 5, 21, 3, 54, 12, 299649, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date for which the data is collected",
            ),
            preserve_default=False,
        ),
    ]
