# Generated by Django 5.0.1 on 2024-05-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0010_alter_campaignentry_for_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignentry",
            name="for_date",
            field=models.DateTimeField(
                db_index=True, verbose_name="Date for which the data is collected"
            ),
        ),
    ]
