# Generated by Django 5.0.1 on 2024-05-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0014_alter_pricechange_attribute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricechange",
            name="new_stock",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricechange",
            name="old_stock",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
