# Generated by Django 5.0.1 on 2024-04-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalCSS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("css", models.TextField(verbose_name="CSS")),
            ],
            options={
                "verbose_name": "CSS",
                "verbose_name_plural": "CSS",
            },
        ),
    ]
