# Generated by Django 5.0.1 on 2024-11-04 00:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_globalsetting"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GlobalSetting",
            new_name="CommonSiteSettings",
        ),
    ]
