# Generated by Django 5.0.1 on 2024-11-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0006_rename_globalsetting_commonsitesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacebookAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Facebook Access Token",
                "verbose_name_plural": "Facebook Access Tokens",
            },
        ),
    ]
