# Generated by Django 5.0.9 on 2024-11-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0007_facebookaccesstoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalcss",
            name="cart_section_five",
            field=models.TextField(
                blank=True, null=True, verbose_name="Cart Section 5"
            ),
        ),
        migrations.AddField(
            model_name="globalcss",
            name="cart_section_four",
            field=models.TextField(
                blank=True, null=True, verbose_name="Cart Section 4"
            ),
        ),
        migrations.AddField(
            model_name="globalcss",
            name="cart_section_one",
            field=models.TextField(
                blank=True, null=True, verbose_name="Cart Section 1"
            ),
        ),
        migrations.AddField(
            model_name="globalcss",
            name="cart_section_six",
            field=models.TextField(
                blank=True, null=True, verbose_name="Cart Section 6"
            ),
        ),
        migrations.AddField(
            model_name="globalcss",
            name="cart_section_three",
            field=models.TextField(
                blank=True, null=True, verbose_name="Cart Section 3"
            ),
        ),
        migrations.AddField(
            model_name="globalcss",
            name="cart_section_two",
            field=models.TextField(
                blank=True, null=True, verbose_name="Cart Section 2"
            ),
        ),
        migrations.AddField(
            model_name="globalcss",
            name="checkout_section_one",
            field=models.TextField(
                blank=True, null=True, verbose_name="Checkout Section 1"
            ),
        ),
        migrations.AddField(
            model_name="globalcss",
            name="checkout_section_three",
            field=models.TextField(
                blank=True, null=True, verbose_name="Checkout Section 3"
            ),
        ),
        migrations.AddField(
            model_name="globalcss",
            name="checkout_section_two",
            field=models.TextField(
                blank=True, null=True, verbose_name="Checkout Section 2"
            ),
        ),
    ]
