let INTERNAL_SHOP_MANAGER_API_BASE_PATH = "/shop-manager/api";
let INTERNAL_STOCK_MANAGER_API_BASE_PATH = "/api/stock"

let ADMIN_URLS = {
  'CHANGE_ORDER_STATUS': INTERNAL_SHOP_MANAGER_API_BASE_PATH + '/change-order-status/',
  'REMOVE_ABANDONED_CART': INTERNAL_SHOP_MANAGER_API_BASE_PATH + '/remove-abandoned-cart/',
  "RETRIEVE_PRODUCT_BY_CODE": INTERNAL_STOCK_MANAGER_API_BASE_PATH + '/stock-item/',
  "UPDATE_STOCK_ITEM": INTERNAL_STOCK_MANAGER_API_BASE_PATH + '/manage-stock-item/'
}

export {ADMIN_URLS};