# Generated by Django 5.0.1 on 2024-01-24 21:47

import ckeditor_uploader.fields
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Име")),
                (
                    "promotion_text",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Текст за промоција",
                    ),
                ),
                (
                    "promotion_image",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True, null=True, upload_to="products/%Y/%m/%d/"
                    ),
                ),
                (
                    "is_on_promotion",
                    models.BooleanField(default=False, verbose_name="Промоција"),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, unique=True, verbose_name="Slug"),
                ),
            ],
            options={
                "verbose_name": "Категорија",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "thumbnail",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True, null=True, upload_to="products/%Y/%m/%d/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Published"),
                            ("out_of_stock", "Out of Stock"),
                            ("archived", "Archived"),
                        ],
                        default="published",
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("simple", "Simple"), ("variable", "Variable")],
                        default="simple",
                        max_length=20,
                    ),
                ),
                ("slug", models.SlugField(blank=True)),
                ("regular_price", models.PositiveIntegerField()),
                ("sale_price", models.PositiveIntegerField(blank=True, null=True)),
                ("description", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "stock_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.stockitem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("color", "Color"),
                            ("size", "Size"),
                            ("offer", "Offer"),
                            ("cart_offer", "Cart Offer"),
                        ],
                        default="color",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("content", models.CharField(max_length=140)),
                ("price", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
