# Generated by Django 5.0.1 on 2024-01-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="has_free_shipping",
            field=models.BooleanField(default=False),
        ),
    ]
