# Generated by Django 5.0.1 on 2024-01-25 19:37

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_product_has_free_shipping"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="shop.category",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="promotion_image",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                null=True,
                upload_to="products/%Y/%m/%d/",
                verbose_name="Слика за промоција (200px X 200px)",
            ),
        ),
    ]
