# Generated by Django 5.0.1 on 2024-01-24 00:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_rename_created_product_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=ckeditor.fields.RichTextField(default="asd"),
            preserve_default=False,
        ),
    ]
