# Generated by Django 5.0 on 2023-12-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_rename_name_product_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[("simple", "Simple"), ("variable", "Variable")],
                default="simple",
                max_length=20,
            ),
        ),
    ]
