# Generated by Django 5.0 on 2023-12-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("out_of_stock", "Out of Stock"),
                    ("archived", "Archived"),
                ],
                default="published",
                max_length=20,
            ),
        ),
    ]
