# Generated by Django 5.0 on 2023-12-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_productattribute"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productattribute",
            old_name="value",
            new_name="content",
        ),
        migrations.AddField(
            model_name="productattribute",
            name="price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="regular_price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="sale_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="type",
            field=models.CharField(
                choices=[
                    ("color", "Color"),
                    ("size", "Size"),
                    ("offer", "Offer"),
                    ("cart_offer", "Cart Offer"),
                ],
                default="color",
                max_length=20,
            ),
        ),
    ]
