# Generated by Django 5.0.1 on 2024-01-28 23:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_remove_product_category_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="category",
            new_name="categories",
        ),
    ]
