# Generated by Django 5.0.1 on 2024-02-17 13:09

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="productattribute",
            name="color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="type",
            field=models.CharField(
                choices=[("color", "Color"), ("size", "Size"), ("offer", "Offer")],
                default="color",
                max_length=20,
            ),
        ),
    ]
