# Generated by Django 5.0.1 on 2024-02-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_productattribute_color_alter_productattribute_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="labelitus",
            field=models.BooleanField(default=False),
        ),
    ]
