# Generated by Django 5.0.1 on 2024-02-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_product_labelitus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="labelitus",
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Наслов"),
        ),
    ]
