# Generated by Django 5.0.1 on 2024-02-22 23:28

import ckeditor_uploader.fields
import colorfield.fields
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_remove_product_labelitus_alter_product_title"),
        ("stock", "0003_alter_import_options_alter_stockitem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Производ", "verbose_name_plural": "Производи"},
        ),
        migrations.AlterModelOptions(
            name="productattribute",
            options={"verbose_name": "Атрибут", "verbose_name_plural": "Атрибути"},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "Рецензија", "verbose_name_plural": "Рецензии"},
        ),
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                related_name="products", to="shop.category", verbose_name="Категории"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="product",
            name="has_free_shipping",
            field=models.BooleanField(default=False, verbose_name="Бесплатна испорака"),
        ),
        migrations.AlterField(
            model_name="product",
            name="regular_price",
            field=models.PositiveIntegerField(verbose_name="Regular price"),
        ),
        migrations.AlterField(
            model_name="product",
            name="sale_price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Sale price"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("out_of_stock", "Out of Stock"),
                    ("archived", "Archived"),
                ],
                default="published",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stock.stockitem",
                verbose_name="Магацински предмет",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[("simple", "Simple"), ("variable", "Variable")],
                default="simple",
                max_length=20,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Боја",
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="content",
            field=models.CharField(max_length=140, verbose_name="Содржина"),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="name",
            field=models.CharField(max_length=140, verbose_name="Име"),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="shop.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="type",
            field=models.CharField(
                choices=[("color", "Color"), ("size", "Size"), ("offer", "Offer")],
                default="color",
                max_length=20,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                upload_to="products/gallery/%Y/%m/%d/", verbose_name="Gallery Image"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="shop.product",
                verbose_name="Производ",
            ),
        ),
    ]
