# Generated by Django 5.0.1 on 2024-02-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0012_alter_product_options_alter_productattribute_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=300, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=300, unique=True, verbose_name="Slug"
            ),
        ),
    ]
