# Generated by Django 5.0.1 on 2024-03-03 16:17

import ckeditor_uploader.fields
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0013_alter_category_slug_alter_product_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Име")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="Содржина"
                    ),
                ),
            ],
            options={
                "verbose_name": "Информативна страница",
                "verbose_name_plural": "Информативни страници",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="promotion_image",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                null=True,
                upload_to="products/%Y/%m/%d/",
                verbose_name="Слика за промоција (150px X 150px)",
            ),
        ),
    ]
