# Generated by Django 5.0.1 on 2024-03-03 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0015_rename_name_brandpage_title"),
        ("stock", "0006_alter_stockitem_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="productattribute",
            name="stock_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stock.stockitem",
                verbose_name="Магацински предмет",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                db_index=True,
                related_name="products",
                to="shop.category",
                verbose_name="Категории",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="has_free_shipping",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Бесплатна испорака"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("out_of_stock", "Out of Stock"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="published",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
