# Generated by Django 5.0.1 on 2024-03-04 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0016_productattribute_stock_item_alter_product_categories_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productattribute",
            name="color",
        ),
    ]
