# Generated by Django 5.0.1 on 2024-03-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0019_category_max_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_default",
            field=models.BooleanField(
                default=False, verbose_name="Стандардна категорија"
            ),
        ),
    ]
