# Generated by Django 5.0.1 on 2024-03-16 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0020_category_is_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrequentlyAskedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(max_length=200, verbose_name="Прашање")),
                ("answer", models.TextField(verbose_name="Одговор")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        verbose_name="Стандардно прашање (Вклучено за секој производ)",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqItems",
                        to="shop.product",
                        verbose_name="Производ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Често поставени прашања",
                "verbose_name_plural": "Често поставени прашања",
            },
        ),
    ]
