# Generated by Django 5.0.1 on 2024-03-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0023_alter_frequentlyaskedquestion_is_default"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productattribute",
            name="price",
        ),
        migrations.AddField(
            model_name="productattribute",
            name="regular_price",
            field=models.PositiveIntegerField(
                default=9999, verbose_name="Цена без попуст"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productattribute",
            name="sale_price",
            field=models.PositiveIntegerField(default=500, verbose_name="Цена"),
            preserve_default=False,
        ),
    ]
