# Generated by Django 5.0.1 on 2024-03-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0024_remove_productattribute_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="short_description",
            field=models.TextField(blank=True, null=True, verbose_name="Краток опис"),
        ),
    ]
