# Generated by Django 5.0.1 on 2024-03-16 22:42

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0025_product_short_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productattribute",
            name="name",
        ),
        migrations.AddField(
            model_name="productattribute",
            name="thumbnail",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, null=True, upload_to="products/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="title",
            field=models.CharField(
                default="test", max_length=255, verbose_name="Наслов"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="promotion_image",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                null=True,
                upload_to="categories/%Y/%m/%d/",
                verbose_name="Слика за промоција (150px X 150px)",
            ),
        ),
    ]
