# Generated by Django 5.0.1 on 2024-03-17 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0026_remove_productattribute_name_and_more"),
        ("stock", "0007_stockitem_reserved_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stock.stockitem",
                verbose_name="Магацински предмет",
            ),
        ),
    ]
