# Generated by Django 5.0.1 on 2024-03-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0028_alter_productattribute_stock_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productattribute",
            name="type",
            field=models.CharField(
                choices=[("color", "боја"), ("size", "големина"), ("offer", "понуда")],
                default="color",
                max_length=20,
                verbose_name="Тип",
            ),
        ),
    ]
