# Generated by Django 5.0.1 on 2024-03-25 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0029_alter_productattribute_type"),
        ("stock", "0014_alter_stockitem_options_alter_stockitem_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stock.stockitem",
                verbose_name="Stock Item",
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="stock_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stock.stockitem",
                verbose_name="Stock Item",
            ),
        ),
    ]
