# Generated by Django 5.0.1 on 2024-03-26 00:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0030_alter_product_stock_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="technical_specifications",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="Технички спецификации"
            ),
        ),
    ]
