# Generated by Django 5.0.1 on 2024-04-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0032_rename_has_free_shipping_product_free_shipping"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["display_order"],
                "verbose_name": "Категорија",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="display_order",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
