# Generated by Django 5.0.1 on 2024-04-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0034_alter_category_display_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="display_order",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
