# Generated by Django 5.0.1 on 2024-04-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0037_remove_category_css_category_banner_css_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="promotion_text_css",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Promotion Text CSS (стави !important)",
            ),
        ),
    ]
