# Generated by Django 5.0.1 on 2024-04-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0038_category_promotion_text_css"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="link_css",
            field=models.TextField(
                blank=True, null=True, verbose_name="Link CSS (стави !important)"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="show_logo_icon",
            field=models.BooleanField(
                default=True,
                verbose_name="Прикажи лого икона (на промотивна категорија)",
            ),
        ),
    ]
