# Generated by Django 5.0.1 on 2024-05-06 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0041_client"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Client",
            new_name="ShopClient",
        ),
        migrations.AlterModelOptions(
            name="shopclient",
            options={"verbose_name": "Клиент", "verbose_name_plural": "Клиенти"},
        ),
    ]
