# Generated by Django 5.0.1 on 2024-05-06 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0042_rename_client_shopclient_alter_shopclient_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShopClient",
        ),
    ]
