# Generated by Django 5.0.1 on 2024-05-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0044_shopclient"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopclient",
            name="total_profit",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shopclient",
            name="total_revenue",
            field=models.IntegerField(default=0),
        ),
    ]
