# Generated by Django 5.0.1 on 2024-05-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0045_shopclient_total_profit_shopclient_total_revenue"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shopclient",
            options={
                "ordering": ["display_order"],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенти",
            },
        ),
        migrations.AddField(
            model_name="shopclient",
            name="display_order",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
