# Generated by Django 5.0.1 on 2024-11-05 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0046_alter_shopclient_options_shopclient_display_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartOffers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "offer_price",
                    models.PositiveIntegerField(verbose_name="Понудена цена"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_offers",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Понуда",
                "verbose_name_plural": "Понуди",
            },
        ),
    ]
