# Generated by Django 5.0.1 on 2024-11-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0047_cartoffers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartoffers",
            options={
                "ordering": ["display_order"],
                "verbose_name": "Понуда за кошничка",
                "verbose_name_plural": "Понуди за кошничка",
            },
        ),
        migrations.AddField(
            model_name="cartoffers",
            name="display_order",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
