# Generated by Django 5.0.1 on 2024-11-07 02:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0048_alter_cartoffers_options_cartoffers_display_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartoffers",
            old_name="offer_price",
            new_name="sale_price",
        ),
    ]
