# Generated by Django 5.0.1 on 2024-11-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0049_rename_offer_price_cartoffers_sale_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartoffers",
            name="sale_text",
            field=models.CharField(
                default="Непропустлива понуда! Купи сега! 🛒🔥",
                max_length=200,
                verbose_name="Текст за понуда",
            ),
            preserve_default=False,
        ),
    ]
