# Generated by Django 5.0.9 on 2024-11-19 01:03

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0050_cartoffers_sale_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSeoTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seo_title",
                    models.CharField(max_length=200, verbose_name="SEO Title"),
                ),
                ("seo_description", models.TextField(verbose_name="SEO Description")),
                (
                    "seo_image",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        null=True,
                        upload_to="products/%Y/%m/%d/",
                        verbose_name="SEO Image",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo_tags",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
