# Generated by Django 5.0.9 on 2024-11-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0051_productseotags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sale_price",
            field=models.PositiveIntegerField(default=0, verbose_name="Sale price"),
            preserve_default=False,
        ),
    ]
