# Generated by Django 5.0.1 on 2024-03-03 20:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=50, unique=True
            ),
            preserve_default=False,
        ),
    ]
