# Generated by Django 5.0.1 on 2024-03-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_order_tracking_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
