# Generated by Django 5.0 on 2023-12-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_order_orderitem_shippingdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="type",
            field=models.CharField(
                choices=[("simple", "Simple"), ("variable", "Variable")],
                default="simple",
                max_length=20,
            ),
        ),
    ]
