# Generated by Django 5.0.1 on 2024-01-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_rename_created_cart_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingdetails",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
