# Generated by Django 5.0.1 on 2024-03-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_alter_order_tracking_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="session_key",
            field=models.CharField(db_index=True, default=None, max_length=40),
        ),
    ]
