# Generated by Django 5.0 on 2023-12-10 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_cartitem_attribute"),
        ("shop", "0006_productattribute"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="attribute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.productattribute",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="type",
            field=models.CharField(
                choices=[("simple", "Simple"), ("variable", "Variable")],
                default="simple",
                max_length=20,
            ),
        ),
    ]
