# Generated by Django 5.0.1 on 2024-03-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_alter_cart_session_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="session_key",
            field=models.CharField(default="asd", max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "непотврдени"),
                    ("confirmed", "потврдени"),
                    ("deleted", "избришени"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
