# Generated by Django 5.0.1 on 2024-03-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0005_alter_order_session_key_alter_order_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_from_promotion",
            field=models.BooleanField(default=False),
        ),
    ]
