# Generated by Django 5.0.1 on 2024-03-17 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0007_shippingdetails_municipality"),
        ("shop", "0027_alter_product_stock_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="attribute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.productattribute",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="shop.product",
            ),
        ),
    ]
