# Generated by Django 5.0.1 on 2024-03-17 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0008_alter_orderitem_attribute_alter_orderitem_product"),
        ("stock", "0008_remove_stockitem_reserved_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="stock_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="stock.stockitem",
            ),
        ),
    ]
