# Generated by Django 5.0.1 on 2024-03-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0009_orderitem_stock_item"),
        ("stock", "0009_reservedstockitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="reserved_stock_items",
            field=models.ManyToManyField(
                related_name="order_items", to="stock.reservedstockitem"
            ),
        ),
    ]
