# Generated by Django 5.0.1 on 2024-03-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0010_orderitem_reserved_stock_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP адреса"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user_agent",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="User Agent"
            ),
        ),
    ]
