# Generated by Django 5.0.1 on 2024-03-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0011_order_ip_order_user_agent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="is_from_promotion",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="promotion_type",
            field=models.CharField(
                blank=True,
                choices=[("thank_you", "thank_you"), ("sidecart", "sidecart")],
                default=None,
                max_length=25,
                null=True,
            ),
        ),
    ]
