# Generated by Django 5.0.1 on 2024-03-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0012_remove_orderitem_is_from_promotion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingdetails",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
