# Generated by Django 5.0.1 on 2024-03-26 03:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0014_order_barcode_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="barcode_image",
            new_name="barcode",
        ),
    ]
