# Generated by Django 5.0.1 on 2024-03-31 14:52

import cart.models
import common.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0016_remove_order_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice",
            field=models.FileField(
                blank=True,
                null=True,
                storage=common.storage.InvoicesStorage(),
                upload_to=cart.models.invoice_upload_to,
            ),
        ),
    ]
