# Generated by Django 5.0.1 on 2024-03-31 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0017_order_invoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="invoice",
        ),
    ]
