# Generated by Django 5.0.1 on 2024-04-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0018_remove_order_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingdetails",
            name="email",
            field=models.TextField(blank=True, null=True),
        ),
    ]
