# Generated by Django 5.0.1 on 2024-04-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0019_alter_shippingdetails_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingdetails",
            name="email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
