# Generated by Django 5.0.1 on 2024-04-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0021_abandonedcartdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abandonedcartdetails",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="abandonedcartdetails",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="abandonedcartdetails",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
