# Generated by Django 5.0.1 on 2024-04-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0024_cart_status_alter_abandonedcartdetails_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="mail_is_sent",
            field=models.BooleanField(default=False),
        ),
    ]
