# Generated by Django 5.0.1 on 2024-04-15 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0026_alter_order_user_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="exportable_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
