# Generated by Django 5.0.1 on 2024-04-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0027_order_exportable_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="rabat",
            field=models.IntegerField(default=0),
        ),
    ]
