# Generated by Django 5.0.1 on 2024-05-03 17:06

import common.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0028_orderitem_rabat"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pdf_invoice",
            field=models.FileField(
                blank=True,
                null=True,
                storage=common.storage.InvoicesStorage(),
                upload_to="invoices/%Y/%m/%d/",
            ),
        ),
    ]
