# Generated by Django 5.0.1 on 2024-05-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0030_remove_orderitem_reserved_stock_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="generate_pdf_invoice",
            field=models.BooleanField(default=True, verbose_name="Генерири фактура"),
        ),
    ]
