# Generated by Django 5.0.1 on 2024-05-16 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0034_order_profit_alter_order_user"),
        ("shop", "0046_alter_shopclient_options_shopclient_display_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="shop.product",
            ),
        ),
    ]
