# Generated by Django 5.0.1 on 2024-11-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0035_alter_orderitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="is_cart_offer",
            field=models.BooleanField(default=False),
        ),
    ]
