# Generated by Django 5.0.1 on 2024-11-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0036_cartitem_is_cart_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_cart_offer",
            field=models.BooleanField(default=False),
        ),
    ]
