# Generated by Django 5.0.1 on 2024-11-07 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0037_orderitem_is_cart_offer"),
        ("shop", "0050_cartoffers_sale_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="is_cart_offer",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart_offer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.cartoffers",
            ),
        ),
    ]
