# Generated by Django 5.1.6 on 2025-02-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0038_remove_cartitem_is_cart_offer_cartitem_cart_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_price",
            field=models.IntegerField(default=140),
        ),
    ]
